@startuml
'https://plantuml.com/sequence-diagram



DrinksMenu -> TextUI: ui = new TextUI()
DrinksMenu -> TextUI: age = ui.promptNumeric("How old are you?")
TextUI -> Scanner: input = nextInt()
Scanner --> TextUI: 11
TextUI --> DrinksMenu: 11


@enduml